apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphonsedev-deployment
spec:
  replicas: 11
  selector:
    matchLabels:
      app: alphonsedev
  template:
    metadata:
      labels:
        app: alphonsedev
    spec:
      containers:
      - name: alphonsedev
        image: 737047471328.dkr.ecr.us-east-1.amazonaws.com/alphonsedev:15
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alphonsedev-service
spec:
  type: LoadBalancer
  selector:
    app: alphonsedev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
